# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestRetainCycle' do
  # Comment the next line if you don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  # Pods for TestRetainCycle
   pod 'LifetimeTracker', '1.8.0'

  target 'TestRetainCycleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestRetainCycleUITests' do
    # Pods for testing
  end

end
